### ISSUE TITLE
How to deploy the smart contract and run the dapp

### ISSUE THREAD

**Issue by souravmaji1** [SabeloMkhwanzi/thirdbnb3#1]
can you please guide me , how can i deploy the smart contract and run the dapp

**Comment by SabeloMkhwanzi** [comment]
@souravmaji1  you can copy the thirdbnb contract on the contract folder, than past its on remix ide its easy to deploy on any test network. but if you gonna use this project, I may warn you the project is outdate and buggy.

**Comment by souravmaji1** [comment]
Can you tell me where I have to add the contract address and abi inside the
front end to run the dapp

**Comment by SabeloMkhwanzi** [comment]
You can past you contract address when to src/components/address.ts

**Comment by souravmaji1** [comment]
I have pasted the contract address in src/component/address.ts

After that i run the dapp, where I can list room but the room is not
displaying in the explore page

Can you able to tell me how to fix it

**Comment by souravmaji1** [comment]
In the console this is the error showing and rooms are not displaying[image:
eee.PNG]

**Comment by SabeloMkhwanzi** [comment]
As mentioned that the project is very buggy, the last time I checked it. So
I decided to put it aside since I don't have enough time to debug it at the
moment my apologies. But with minor reference I will try to assist.

**Comment by souravmaji1** [comment]
I am very close so, if you just help me to display the rooms in the explore
page it will. Be really helpfull
